sisinvestigacion/apps/proyecto/urls.py
from django.conf.urls import patterns, url, include
from .views import *

urlpatterns = [
	#este es mi primer index
    url(r'^registro_proyecto/$', registro_proyecto),
    url(r'^actualizar_proyecto/$', actualizar_proyecto),
    url(r'^eliminar_proyecto/$', eliminar_proyecto),
    url(r'^cambiarestado$', cambiarestado),
    url(r'^busq_ajax_pro/$', busq_ajax_pro),
    
    url(r'^traerparticipantes$', traerparticipantes),
    url(r'^mostrarparticipante$', mostrarparticipante),
    url(r'^actualizarparticipante$', actualizarparticipante),
    url(r'^mostrarproyecto$', mostrarproyecto),

    #agregar docente
    url(r'^adocente$', Adocente),

    #agregar docente
    url(r'^aalumno$', Aalumno),

    #agregar docente
    url(r'^aadministrativo$', Aadministrativo),

    #agregar docente
    url(r'^aexterno$', Aexterno),

    #solicitud
    url(r'^mostrarsolicitud$', mostrarsolicitud),    
    url(r'^editarsolicitud$', editarsolicitud),       

    #informe
    url(r'^registro_informe/$', registro_informe),  
    url(r'^mostrarinforme$', mostrarinforme),  
    url(r'^editarinforme$', editarinforme),      

    #resolucion
    url(r'^registro_resolucion/$', registro_resolucion),  
    url(r'^mostrarresolucion$', mostrarresolucion),  
    url(r'^editarresolucion$', editarresolucion),      


]

sisinvestigacion/sisinvestigacion/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve 

urlpatterns = [ 
    # Examples:
    # url(r'^$', 'clase1.views.home', name='home'),
    url(r'^media/(?P<path>.*)$', serve , {'document_root': settings.MEDIA_ROOT, }),
    url(r'^', include('apps.busqueda.urls')),
    url(r'^', include('apps.proyecto.urls')),
    url(r'^', include('apps.matenimiento.urls')),
    url(r'^', include('apps.reportes.urls')),
    url(r'^', include('apps.seguridad.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

sisinvestigacion/apps/proyecto/models.py
from django.db import models
from apps.matenimiento.models import modalidad_participante, oficina, alumno, docente, semestre_academico, estado, administrativo, externo


class solicitud(models.Model):
    nombresolicitud   = models.CharField(max_length=100)
    asuntosolicitud   = models.CharField(max_length=300)
    proveidosolicitud = models.CharField(max_length=200)
    fechadocumento    = models.DateField()
    archivosolicitud  = models.FileField(upload_to='Solicitud/%Y/%m/%d')
    estado            = models.BooleanField(default=True)

class informe(models.Model):
    numeroinforme   = models.CharField(max_length=100)
    asuntoinforme   = models.CharField(max_length=300)
    proveidoinforme = models.CharField(max_length=300)
    fechadocumento  = models.DateField()
    fechaenvio      = models.DateField()
    archivoinforme  = models.FileField(upload_to='Informe/%Y/%m/%d')
    idoficina       = models.ForeignKey(oficina,null=True)
    estado          = models.BooleanField(default=True)

class resolucion(models.Model):
    numeroresolucion    = models.CharField(max_length=20)
    asuntoresolucion    = models.CharField(max_length=300)
    proveidoresolucion  = models.CharField(max_length=200)
    fechadocumento      = models.DateField()
    #fecharecepcion      = models.DateField()
    fechaenvio          = models.DateField()
    archivoresolucion   = models.FileField(upload_to='Resolucion/%Y/%m/%d')
    idoficina           = models.ForeignKey(oficina,null=True) 
    estado              = models.BooleanField(default=True)



class proyecto(models.Model):
    documento       = models.CharField(max_length=200)
    fecharecepcion  = models.DateField()
    fechaemision    = models.DateField(null=True)
    fechainicio     = models.DateField()
    fechatermino    = models.DateField()
    asunto          = models.TextField(max_length=500)
    proveido        = models.CharField(max_length=200,null=True)
    archivo         = models.FileField(upload_to='Proyecto/%Y/%m/%d')
    observacion     = models.TextField(max_length=500,null=True)
    idsemestre      = models.ForeignKey(semestre_academico)
    idsolicitud     = models.ForeignKey(solicitud,null=True)
    idinforme       = models.ForeignKey(informe,null=True)
    idresolucion    = models.ForeignKey(resolucion,null=True)
    idestado        = models.ForeignKey(estado)
    idalumno        = models.ManyToManyField(alumno, through='proyeAl')
    idadministrativo = models.ManyToManyField(administrativo, through='proyeAd')
    idexterno        = models.ManyToManyField(externo, through='proyeEx')
    iddocente       = models.ManyToManyField(docente, through='proyeDo')
    estado          = models.BooleanField(default=True)

class proyeAl(models.Model):
    idalumno         = models.ForeignKey(alumno)
    idproyectoalumno = models.ForeignKey(proyecto)
    modalidadalumno  = models.ForeignKey(modalidad_participante)


class proyeDo(models.Model):
    iddocente         = models.ForeignKey(docente)
    idproyectodocente = models.ForeignKey(proyecto)
    modalidaddocente  = models.ForeignKey(modalidad_participante)

class proyeEx(models.Model):
    idpexterno  = models.ForeignKey(externo)
    idproyectoexterno = models.ForeignKey(proyecto)
    modalidadexterno = models.ForeignKey(modalidad_participante)

class proyeAd(models.Model):
    idadministrativo = models.ForeignKey(administrativo)
    idproyectoadministrativo = models.ForeignKey(proyecto)
    modalidadadministrativo  = models.ForeignKey(modalidad_participante)

sisinvestigacion/apps/proyecto/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Max, Q
from django.http import JsonResponse
from apps.seguridad.models import permisos
from apps.reportes.models import historial
from apps.matenimiento.models import alumno, docente, semestre_academico, estado, modalidad_participante, oficina, administrativo, externo
from .forms import formproyecto, formSolicitud, formInforme, formResolucion, formDocente, formAlumno, formAdministrativo, formExterno
from .models import proyecto, solicitud, proyeAl, proyeDo, proyeAd,proyeEx, informe, resolucion
from apps.paginacion import paginacion
import datetime, time
today  = datetime.datetime.now()
fecha  = today.strftime("%Y-%m-%d")
hora   = time.strftime("%H:%M:%S") 

#Crea tus vista aqui.
def historiales(request,mod):
    ip        = request.META['REMOTE_ADDR']
    equipo    = request.META['HTTP_USER_AGENT']
    a = historial()
    a.idusuario_id  = request.user.id
    a.fecha         = fecha
    a.hora          = hora
    a.equipo        = equipo
    a.ip            = ip 
    a.modulo        = mod[0]
    a.accion        = mod[1]
    a.idaccion      = mod[2]
    a.save()


def permi(request,url):
    idp = request.user.idperfil_id
    mod = permisos.objects.filter(idmodulo__url=url, idperfil_id=idp).values('idmodulo__url','buscar','eliminar','editar','insertar','imprimir','ver')
    return mod

@login_required(login_url='/')
def registro_proyecto(request):
    
    estados =  permi(request, "registro_proyecto")
    listaAlumnos = [{'id':con.id,'nombre':con.nombre} for con in alumno.objects.filter(estadosistema= True)]
    listaDocentes = [{'id':con.id,'nombre':con.nombre} for con in docente.objects.filter(estadosistema= True)]
    listaEstado = [{'id':con.id, 'descripcion':con.descripcion} for con in estado.objects.filter(estadosistema= True)]   
    listaSemestre = [{'id':con.id, 'descripcion':con.descripcion} for con in semestre_academico.objects.filter(estadosistema= True).order_by('-id')]    

    if request.method == 'POST': 
        idd = request.POST["id"]
        if idd == "undefined":
            idSemestre = semestre_academico.objects.latest('id')
            idc = idSemestre.id
            formuP = formproyecto(request.POST,request.FILES )
            formuS = formSolicitud(request.POST,request.FILES )
            if formuP.is_valid() and formuS.is_valid():
                formuP.save()
                formuS.save()
                idp = proyecto.objects.latest('id')
                ids = solicitud.objects.latest('id')
                pp = proyecto.objects.get(pk=idp.id)
                pp.idsolicitud_id = int(ids.id)
                pp.save()
                
                lid = zip(request.POST.getlist('iddocente[]'), request.POST.getlist('modalidaddocente[]'))
                for i,j in lid: 
                    
                    try:
                        iss = proyeDo.objects.latest('id')
                        iss = iss.id
                    except proyeDo.DoesNotExist:
                        iss = 0

                    doc = proyeDo()
                    doc.id                   = iss + 1 
                    doc.idproyectodocente_id = idp.id
                    doc.modalidaddocente_id  = j
                    doc.iddocente_id         = i
                    doc.save()

                lia = zip(request.POST.getlist('idalumno[]'), request.POST.getlist('modalidadalumno[]'))
                for i,j in lia: 
                    try:
                        iss = proyeAl.objects.latest('id')
                        iss = iss.id
                    except proyeAl.DoesNotExist:
                        iss = 0

                    al = proyeAl()
                    al.id                  = iss + 1   
                    al.idproyectoalumno_id = idp.id
                    al.modalidadalumno_id  = j
                    al.idalumno_id         = i
                    al.save()

                liad = zip(request.POST.getlist('idadmistrativo[]'), request.POST.getlist('modalidadadmistrativo[]'))
                for i,j in liad: 
                    try:
                        iss = proyeAd.objects.latest('id')
                        iss = iss.id
                    except proyeAd.DoesNotExist:
                        iss = 0
                    ad = proyeAd()            
                    ad.id                          = iss + 1 
                    ad.idproyectoadministrativo_id = idp.id
                    ad.modalidadadministrativo_id  = j
                    ad.idadministrativo_id         = i
                    ad.save()    

                liex = zip(request.POST.getlist('idexterno[]'), request.POST.getlist('modalidadexterno[]'))
                for i,j in liex: 
                    try:
                        iss = proyeEx.objects.latest('id')
                        iss = iss.id
                    except proyeEx.DoesNotExist:
                        iss = 0

                    ex = proyeEx()
                    ex.id                   = iss + 1 
                    ex.idproyectoexterno_id = idp.id
                    ex.modalidadexterno_id  = j
                    ex.idpexterno_id        = i
                    ex.save()

                historiales(request,["solicitud","registrar",ids.id])
                historiales(request,["proyecto","registrar",idp.id])
            else:
                return render(request,'proyecto/proyecto/form_pro.html',{'formu':formuP})
        else:
            idc = request.POST["id"]
        
        proyectos = proyecto.objects.filter(idsemestre= idc, estado= True).order_by('-id')  
        return render(request,'proyecto/proyecto/ajax_proyecto.html',{'lista':proyectos,'n':'proyectoU','estado':estados})            
    else:
        ids= semestre_academico.objects.latest('id')
        proyectos = proyecto.objects.filter(idsemestre= ids.id, estado= True).order_by('-id')
        formu = formproyecto()
        modulo = {'formu':formu, 'url':'registro_proyecto/','n':'proyectoU','estado':estados,'idalumno':listaAlumnos, 'iddocente':listaDocentes, 'idestado':listaEstado, 'idsemestre_academico':listaSemestre}
        return paginacion(request,proyectos, modulo, 'proyecto/proyecto/proyecto.html' )        

@login_required(login_url='/')
def actualizar_proyecto(request):
    proyectos = proyecto.objects.filter(estado= True).order_by('-id')
    estado =  permi(request, "registro_proyecto")
    if request.method == 'POST': 
        idp = request.POST.get("id","")
        a=get_object_or_404(proyecto,pk=idp)
        form=formproyecto(request.POST, request.FILES, instance=a)
        if form.is_valid():
            form.save()       
            historiales(request,["proyecto","actualizar",idp])
            return render(request,'proyecto/proyecto/ajax_proyecto.html',{'lista':proyectos,'n':'proyectoU','estado':estado}) 
        else:
            return render(request,'proyecto/proyecto/form_proA.html',{'formu':form})             
    else:
        idp = request.GET.get("id","")
        a=get_object_or_404(proyecto,pk=idp)
        form= formproyecto(instance=a)
        return render(request,'proyecto/proyecto/modal.html',{'formu':form,'url':'actualizar_proyecto/','n':'proyectoU','u':'proyectoU','estado':estado})  


@login_required(login_url='/')
def eliminar_proyecto(request):
    proyectos = proyecto.objects.filter(estado= True).order_by('-id')
    estado =  permi(request, "registro_proyecto")
    if request.method == 'GET' and request.is_ajax(): 
        idb = request.GET.get("id","")
        get_object_or_404(proyectos,pk=idb).delete()
        historiales(request,["proyecto","eliminar",idb])
        return render(request,'proyecto/proyecto/ajax_proyecto.html',{'lista':proyectos,'n':'proyectoU','estado':estado})     

@login_required(login_url='/')
def mostrarproyecto(request):
    proyectos = proyecto.objects.filter(pk = request.GET['id'])
    return render(request,'proyecto/proyecto/mostrarproyecto.html',{'lista':proyectos})

@login_required(login_url='/')
def mostrarsolicitud(request):
    solicitudes = proyecto.objects.filter(pk = request.GET['id'])
    return render(request,'proyecto/proyecto/mostrarsolicitud.html',{'lista':solicitudes})  

@login_required(login_url='/')
def editarsolicitud(request):
    if request.method == 'POST': 
        idp = request.POST['id']
        solicitudes = proyecto.objects.filter(idsolicitud_id = idp)
        a=get_object_or_404(solicitud,pk=idp)
        form=formSolicitud(request.POST, request.FILES, instance=a)
        if form.is_valid():
            form.save()       
            historiales(request,["solicitud","actualizar",idp])
            return render(request,'proyecto/proyecto/mostrarsolicitud.html',{'lista':solicitudes}) 

             
        else:
            return render(request,'proyecto/proyecto/form_soli.html',{'formu':form})             
    else:
        idp = request.GET["id"]
        a=get_object_or_404(solicitud,pk=idp)
        formuS = formSolicitud(instance=a)
        return render(request,'proyecto/proyecto/modalS.html',{'nombre':formuS,'url':'editarsolicitud','n':'solicitudU','u':'solicitudU','i':idp}) 

    


@login_required(login_url='/')
def traerparticipantes(request):
    data= []
    doc = []
    alu = []
    adm = []
    otr = []
    mod = []
    par = []
    for con in docente.objects.filter(estadosistema= True).order_by('-id'):
        doc.append({'idd':con.id,'nombres':con.nombre + ' '+ con.apellido, 'codigo':con.codigo})

    for con in alumno.objects.filter(estadosistema= True).order_by('-id'):
        alu.append({'idd':con.id,'nombres':con.nombre + ' '+ con.apellido, 'codigo':con.codigo})

    for con in administrativo.objects.filter(estadosistema= True).order_by('-id'):
        adm.append({'idd':con.id,'nombres':con.nombre + ' '+ con.apellido, 'codigo':con.codigo})

sisinvestigacion/apps/proyecto/templates/proyecto/proyecto/informe/form_in.html
{% csrf_token %}
<div class="ibox-content">
 <div class="row">
   <div class="col-md-6 b-r">
    <label for="id_idoficina" 
    {% if formu.idoficina.errors %}
      {% for error in formu.idoficina.errors %}
        data-html="true" data-toggle="popover" data-content="
            <p style='color:red; font-size: 13px; margin: 0 0 0px;'> {{ error|escape }}</p>
        "
      {% endfor %}
    {% endif %}
    >Oficina:</label>
    {{formu.idoficina.errors}}
    {{formu.idoficina}}      

  

    <label for="id_numeroinforme" 
    {% if formu.numeroinforme.errors %}
      {% for error in formu.numeroinforme.errors %}
        data-html="true" data-toggle="popover" data-content="
            <p style='color:red; font-size: 13px; margin: 0 0 0px;'> {{ error|escape }}</p>
        "
      {% endfor %}
    {% endif %}
    >numero de informe:</label>
    {{formu.numeroinforme.errors}}
    {{formu.numeroinforme}}    

    <label for="id_proveidoinforme" 
    {% if formu.proveidoinforme.errors %}
      {% for error in formu.proveidoinforme.errors %}
        data-html="true" data-toggle="popover" data-content="
            <p style='color:red; font-size: 13px; margin: 0 0 0px;'> {{ error|escape }}</p>
        "
      {% endfor %}
    {% endif %}
    >Proveido:</label>
    {{formu.proveidoinforme.errors}}
    {{formu.proveidoinforme}} 

    <label for="id_fechadocumento" 
    {% if formu.fechadocumento.errors %}
      {% for error in formu.fechadocumento.errors %}
        data-html="true" data-toggle="popover" data-content="
            <p style='color:red; font-size: 13px; margin: 0 0 0px;'> {{ error|escape }}</p>
        "
      {% endfor %}
    {% endif %}
    >fecha de documento:</label>
    {{formu.fechadocumento.errors}}
    {{formu.fechadocumento}}    

    <label for="id_fechaenvio" 
    {% if formu.fechaenvio.errors %}
      {% for error in formu.fechaenvio.errors %}
        data-html="true" data-toggle="popover" data-content="
            <p style='color:red; font-size: 13px; margin: 0 0 0px;'> {{ error|escape }}</p>
        "
      {% endfor %}
    {% endif %}
    >fecha de envio:</label>
    {{formu.fechaenvio.errors}}
    {{formu.fechaenvio}}   

   </div>
   <div class="col-md-6">
    <label for="id_asuntoinforme" 
    {% if formu.asuntoinforme.errors %}
      {% for error in formu.asuntoinforme.errors %}
        data-html="true" data-toggle="popover" data-content="
            <p style='color:red; font-size: 13px; margin: 0 0 0px;'> {{ error|escape }}</p>
        "
      {% endfor %}
    {% endif %}
    >Asunto:</label>
    {{formu.asuntoinforme.errors}}
    {{formu.asuntoinforme}}    
 
    <label for="id_archivoinforme" 
    {% if formu.archivoinforme.errors %}
      {% for error in formu.archivoinforme.errors %}
        data-html="true" data-toggle="popover" data-content="
            <p style='color:red; font-size: 13px; margin: 0 0 0px;'> {{ error|escape }}</p>
        "
      {% endfor %}
    {% endif %}
    >archivo de informe:</label>
    {{formu.archivoinforme.errors}}
    {{formu.archivoinforme}}            
   </div>
  </div>
</div>

      

sisinvestigacion/apps/proyecto/templates/proyecto/proyecto/informe/modalinforme.html
<div id="Modal{{n}}" class="modal fade in" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                 <h1>{{n}}</h1>
                 <form method="post" id="formulario{{n}}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-md-6 b-r">
                                <label for="id_idoficina">Oficina:</label>
                                {{nombre.idoficina}}
                                <label for="id_numeroinforme">Número del informe:</label>
                                {{nombre.numeroinforme}}
                                <label for="id_proveidoinforme">Proveido del informe:</label>
                                {{nombre.proveidoinforme}}
                                <label for="id_fechadocumento">Fecha de documento:</label>
                                {{nombre.fechadocumento}}
                                <label for="id_fechaenvio">Fecha de envio:</label>
                                {{nombre.fechaenvio}}
                            </div>

                            <div class="col-md-6">
                                <label for="id_asuntoinforme">Asunto del informe:</label>
                                {{nombre.asuntoinforme}}
                                <label for="id_archivoinforme">Archivo del informe:</label>
                                {{nombre.archivoinforme}}
                                
                            </div>                        
                        </div>                    
                    </div>
                 </form> 
                
            </div>
            <div class="modal-footer">
                <button class="btn btn-sm btn-primary guar" onclick="guardar{{f}}('{{url}}','{{n}}','{{u}}')"id="{{i}}" type="button">guardar</button>
                <button type="button"  class="btn btn-sm  btn-danger" data-dismiss="modal"> Cancelar</button>
            </div>
        </div>

    </div>
</div>

sisinvestigacion/apps/proyecto/templates/proyecto/proyecto/informe/mostrarinforme.html
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
    <br>
        <ol class="breadcrumb">
            <li>
                <a href="/">Home</a>
            </li>
            <li class="active">
                <strong>Mostrar Informe</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2"></div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title form-inline">
                  <button type="button" onclick="cargar('registro_proyecto')" class="btn btn-white"><i class="fa fa-chevron-left"></i> Atrás</button> <br>                   
                  
                </div>
                <div class="ibox-content table-responsive">
                  
                  {% for p in lista  %}
                    <div class="rows container" style="width:100%">
                      <div class="col-md-8 b-r">
                        <h2><strong>Informe:</strong></h2>
                        <p>{{p.idinforme.numeroinforme}}</p><br>
                      </div>
                      <div class="col-md-4">
                        <label>Fecha de Informe:</label><br>
                        {{p.idinforme.fechadocumento}}<br><br>                      
     
                      </div>
                    </div>
                    <hr>

                    <div class="rows">
                      <div class="col-md-4 b-r">
                        <label>Proveido:</label> <p>{{p.idinforme.proveidoinforme}}</p>

                        <label>Archivo del Informe:</label><br>
                        <a href="media/{{p.idinforme.archivoinforme}}" target="_blank">→ ver Informe</a><br><br>                  

                      </div>
                      <div class="col-md-4 b-r">
                        <label>Asunto:</label><br>
                        <p>{{p.idinforme.asuntoinforme}}</p>                        
                       
                      </div>                      
                      <div class="col-md-4">
                        <label>Editar Solicitud:</label><br>
                        <a class="btn btn-white" href="#informe" 
                        onclick="editarinforme('{{p.idinforme.id}}')" >Editar</a>

                      </div>
                          
                    </div>
                  {% endfor %}                      
                </div>
                
            </div>
        </div>
    </div>
</div>
<div class="informeM"></div>
<div class="modalP"></div>
            
{% load static from  staticfiles %}
<script src="{%static 'js/base.js' %}"></script>
<script src="{%static 'js/modal.js' %}"></script>
<script src="{%static 'js/proyecto.js' %}"></script>
<script src="{%static 'js/proyecto-informe.js' %}"></script>