sisinvestigacion/apps/proyecto/urls.py
from django.conf.urls import patterns, url, include
from .views import *

urlpatterns = [
	#este es mi primer index
    url(r'^registro_proyecto/$', registro_proyecto),
    url(r'^actualizar_proyecto/$', actualizar_proyecto),
    url(r'^eliminar_proyecto/$', eliminar_proyecto),
    url(r'^cambiarestado$', cambiarestado),
    url(r'^busq_ajax_pro/$', busq_ajax_pro),
    
    url(r'^traerparticipantes$', traerparticipantes),
    url(r'^mostrarparticipante$', mostrarparticipante),
    url(r'^actualizarparticipante$', actualizarparticipante),
    url(r'^mostrarproyecto$', mostrarproyecto),

    #agregar docente
    url(r'^adocente$', Adocente),

    #agregar docente
    url(r'^aalumno$', Aalumno),

    #agregar docente
    url(r'^aadministrativo$', Aadministrativo),

    #agregar docente
    url(r'^aexterno$', Aexterno),

    #solicitud
    url(r'^mostrarsolicitud$', mostrarsolicitud),    
    url(r'^editarsolicitud$', editarsolicitud),       

    #informe
    url(r'^registro_informe/$', registro_informe),  
    url(r'^mostrarinforme$', mostrarinforme),  
    url(r'^editarinforme$', editarinforme),      

    #resolucion
    url(r'^registro_resolucion/$', registro_resolucion),  
    url(r'^mostrarresolucion$', mostrarresolucion),  
    url(r'^editarresolucion$', editarresolucion),      


]

sisinvestigacion/sisinvestigacion/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve 

urlpatterns = [ 
    # Examples:
    # url(r'^$', 'clase1.views.home', name='home'),
    url(r'^media/(?P<path>.*)$', serve , {'document_root': settings.MEDIA_ROOT, }),
    url(r'^', include('apps.busqueda.urls')),
    url(r'^', include('apps.proyecto.urls')),
    url(r'^', include('apps.matenimiento.urls')),
    url(r'^', include('apps.reportes.urls')),
    url(r'^', include('apps.seguridad.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

sisinvestigacion/apps/matenimiento/models.py
from django.db import models

class docente(models.Model):
    nombre        = models.CharField(max_length=100)
    apellido      = models.CharField(max_length=100)
    codigo        = models.CharField(max_length=20)
    dni           = models.CharField(max_length=8, null=True)
    correo        = models.CharField(max_length=100,null=True)
    estadosistema = models.BooleanField(default=True)

class alumno(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=150)
    codigo = models.CharField(max_length=8, unique=True)
    estadosistema = models.BooleanField(default=True)

class oficina(models.Model):
    oficina = models.CharField(max_length=100)
    estadosistema = models.BooleanField(default=True)

class modalidad_participante(models.Model):
    descripcion = models.CharField(max_length=100)
    estadosistema = models.BooleanField(default=True)


class estado(models.Model):
    descripcion = models.CharField(max_length=100)
    estadosistema = models.BooleanField(default=True)

class semestre_academico(models.Model):
    descripcion = models.CharField(max_length=8)
    fechainicio = models.DateField()
    fechatermino = models.DateField()
    estadosistema = models.BooleanField(default=True)

class externo(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=150)
    dni = models.CharField(max_length=8, null=True)
    codigo = models.CharField(max_length=20)
    celular = models.CharField(max_length=10,null=True)
    formacionacademica = models.CharField(max_length=200,null=True)
    ocupacion = models.CharField(max_length=100, null=True)
    centrolabores = models.CharField(max_length=100, null=True)
    estadosistema = models.BooleanField(default=True)

class administrativo(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=150)
    dni = models.CharField(max_length=8, null=True)
    codigo = models.CharField(max_length=20)
    celular = models.CharField(max_length=10,null=True)
    ocupacion = models.CharField(max_length=100, null=True)
    idoficina = models.ForeignKey(oficina, null=True)
    estadosistema = models.BooleanField(default=True)

sisinvestigacion/apps/seguridad/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class perfil(models.Model):
    descripcion = models.CharField(max_length=100)

class UserManager(BaseUserManager):
    
    def _create_user(self, usuario, email,password,is_staff, is_superuser, **extra_fields):
        if not email:
            return ValueError('email es obligatorio')
        email = self.normalize_email(email)
        user = self.model(usuario=usuario, email=email, is_active=True,
            is_staff=is_staff, is_superuser = is_superuser, **extra_fields)
        user.set_password(password)
        user.save(using = self._db)
        return User
    def create_user(self, usuario, email, password= None, **extra_fields):
        return self._create_user(usuario,email,password,False,False, **extra_fields)

    def create_superuser(self,usuario,email,password=None, **extra_fields):
        return self._create_user(usuario,email,password, True,True, **extra_fields)
        

class User(AbstractBaseUser, PermissionsMixin):
    usuario   = models.CharField(max_length=50, unique=True)  
    email     = models.EmailField(max_length=50, unique=True)
    nombres   = models.CharField(max_length=100,null=True)
    apellidos = models.CharField(max_length=100,null=True)
    dni       = models.CharField(max_length=8,null=True)  
    telefono  = models.IntegerField(null=True)
    idperfil  = models.ForeignKey(perfil,null=True)

    objects = UserManager()

    is_active = models.BooleanField(default=True)
    is_staff  = models.BooleanField(default=False)
    estado    = models.BooleanField(default=True)
    foto      = models.FileField(upload_to='fotoPerfil')

    USERNAME_FIELD = 'usuario'
    REQUIRED_FIELDS = ['email']

    def get_short_name(self):
        return self.usuario


class modulos(models.Model):
    id = models.AutoField(primary_key=True)
    descripcion = models.CharField(max_length=100)
    padre       = models.IntegerField()
    url         = models.CharField(max_length=150)
    icon        = models.CharField(max_length=150)
    estado      = models.BooleanField(default=True)

class permisos(models.Model):
    ver         = models.BooleanField(default=True)
    buscar      = models.BooleanField(default=True)
    editar      = models.BooleanField(default=True)
    insertar    = models.BooleanField(default=True)
    eliminar    = models.BooleanField(default=True)
    imprimir    = models.BooleanField(default=True)
    idmodulo    = models.ForeignKey(modulos) 
    idperfil    = models.ForeignKey(perfil)


class galeria(models.Model):
    nombre   = models.CharField(max_length=500)
    clase    = models.CharField(max_length=50)
    estado   = models.BooleanField(default=True)


class fotos(models.Model):
    url          = models.FileField(upload_to='fotoGaleria')     
    titulo       = models.CharField(max_length=150)
    descripcion  = models.CharField(max_length=500)
    idgaleria    = models.ForeignKey(galeria) 
    estado       = models.BooleanField(default=True)

sisinvestigacion/apps/proyecto/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Max, Q
from django.http import JsonResponse
from apps.seguridad.models import permisos
from apps.reportes.models import historial
from apps.matenimiento.models import alumno, docente, semestre_academico, estado, modalidad_participante, oficina, administrativo, externo
from .forms import formproyecto, formSolicitud, formInforme, formResolucion, formDocente, formAlumno, formAdministrativo, formExterno
from .models import proyecto, solicitud, proyeAl, proyeDo, proyeAd,proyeEx, informe, resolucion
from apps.paginacion import paginacion
import datetime, time
today  = datetime.datetime.now()
fecha  = today.strftime("%Y-%m-%d")
hora   = time.strftime("%H:%M:%S") 

#Crea tus vista aqui.
def historiales(request,mod):
    ip        = request.META['REMOTE_ADDR']
    equipo    = request.META['HTTP_USER_AGENT']
    a = historial()
    a.idusuario_id  = request.user.id
    a.fecha         = fecha
    a.hora          = hora
    a.equipo        = equipo
    a.ip            = ip 
    a.modulo        = mod[0]
    a.accion        = mod[1]
    a.idaccion      = mod[2]
    a.save()


def permi(request,url):
    idp = request.user.idperfil_id
    mod = permisos.objects.filter(idmodulo__url=url, idperfil_id=idp).values('idmodulo__url','buscar','eliminar','editar','insertar','imprimir','ver')
    return mod

@login_required(login_url='/')
def registro_proyecto(request):
    
    estados =  permi(request, "registro_proyecto")
    listaAlumnos = [{'id':con.id,'nombre':con.nombre} for con in alumno.objects.filter(estadosistema= True)]
    listaDocentes = [{'id':con.id,'nombre':con.nombre} for con in docente.objects.filter(estadosistema= True)]
    listaEstado = [{'id':con.id, 'descripcion':con.descripcion} for con in estado.objects.filter(estadosistema= True)]   
    listaSemestre = [{'id':con.id, 'descripcion':con.descripcion} for con in semestre_academico.objects.filter(estadosistema= True).order_by('-id')]    

    if request.method == 'POST': 
        idd = request.POST["id"]
        if idd == "undefined":
            idSemestre = semestre_academico.objects.latest('id')
            idc = idSemestre.id
            formuP = formproyecto(request.POST,request.FILES )
            formuS = formSolicitud(request.POST,request.FILES )
            if formuP.is_valid() and formuS.is_valid():
                formuP.save()
                formuS.save()
                idp = proyecto.objects.latest('id')
                ids = solicitud.objects.latest('id')
                pp = proyecto.objects.get(pk=idp.id)
                pp.idsolicitud_id = int(ids.id)
                pp.save()
                
                lid = zip(request.POST.getlist('iddocente[]'), request.POST.getlist('modalidaddocente[]'))
                for i,j in lid: 
                    
                    try:
                        iss = proyeDo.objects.latest('id')
                        iss = iss.id
                    except proyeDo.DoesNotExist:
                        iss = 0

                    doc = proyeDo()
                    doc.id                   = iss + 1 
                    doc.idproyectodocente_id = idp.id
                    doc.modalidaddocente_id  = j
                    doc.iddocente_id         = i
                    doc.save()

                lia = zip(request.POST.getlist('idalumno[]'), request.POST.getlist('modalidadalumno[]'))
                for i,j in lia: 
                    try:
                        iss = proyeAl.objects.latest('id')
                        iss = iss.id
                    except proyeAl.DoesNotExist:
                        iss = 0

                    al = proyeAl()
                    al.id                  = iss + 1   
                    al.idproyectoalumno_id = idp.id
                    al.modalidadalumno_id  = j
                    al.idalumno_id         = i
                    al.save()

                liad = zip(request.POST.getlist('idadmistrativo[]'), request.POST.getlist('modalidadadmistrativo[]'))
                for i,j in liad: 
                    try:
                        iss = proyeAd.objects.latest('id')
                        iss = iss.id
                    except proyeAd.DoesNotExist:
                        iss = 0
                    ad = proyeAd()            
                    ad.id                          = iss + 1 
                    ad.idproyectoadministrativo_id = idp.id
                    ad.modalidadadministrativo_id  = j
                    ad.idadministrativo_id         = i
                    ad.save()    

                liex = zip(request.POST.getlist('idexterno[]'), request.POST.getlist('modalidadexterno[]'))
                for i,j in liex: 
                    try:
                        iss = proyeEx.objects.latest('id')
                        iss = iss.id
                    except proyeEx.DoesNotExist:
                        iss = 0

                    ex = proyeEx()
                    ex.id                   = iss + 1 
                    ex.idproyectoexterno_id = idp.id
                    ex.modalidadexterno_id  = j
                    ex.idpexterno_id        = i
                    ex.save()

                historiales(request,["solicitud","registrar",ids.id])
                historiales(request,["proyecto","registrar",idp.id])
            else:
                return render(request,'proyecto/proyecto/form_pro.html',{'formu':formuP})
        else:
            idc = request.POST["id"]
        
        proyectos = proyecto.objects.filter(idsemestre= idc, estado= True).order_by('-id')  
        return render(request,'proyecto/proyecto/ajax_proyecto.html',{'lista':proyectos,'n':'proyectoU','estado':estados})            
    else:
        ids= semestre_academico.objects.latest('id')
        proyectos = proyecto.objects.filter(idsemestre= ids.id, estado= True).order_by('-id')
        formu = formproyecto()
        modulo = {'formu':formu, 'url':'registro_proyecto/','n':'proyectoU','estado':estados,'idalumno':listaAlumnos, 'iddocente':listaDocentes, 'idestado':listaEstado, 'idsemestre_academico':listaSemestre}
        return paginacion(request,proyectos, modulo, 'proyecto/proyecto/proyecto.html' )        

@login_required(login_url='/')
def actualizar_proyecto(request):
    proyectos = proyecto.objects.filter(estado= True).order_by('-id')
    estado =  permi(request, "registro_proyecto")
    if request.method == 'POST': 
        idp = request.POST.get("id","")
        a=get_object_or_404(proyecto,pk=idp)
        form=formproyecto(request.POST, request.FILES, instance=a)
        if form.is_valid():
            form.save()       
            historiales(request,["proyecto","actualizar",idp])
            return render(request,'proyecto/proyecto/ajax_proyecto.html',{'lista':proyectos,'n':'proyectoU','estado':estado}) 
        else:
            return render(request,'proyecto/proyecto/form_proA.html',{'formu':form})             
    else:
        idp = request.GET.get("id","")
        a=get_object_or_404(proyecto,pk=idp)
        form= formproyecto(instance=a)
        return render(request,'proyecto/proyecto/modal.html',{'formu':form,'url':'actualizar_proyecto/','n':'proyectoU','u':'proyectoU','estado':estado})  


@login_required(login_url='/')
def eliminar_proyecto(request):
    proyectos = proyecto.objects.filter(estado= True).order_by('-id')
    estado =  permi(request, "registro_proyecto")
    if request.method == 'GET' and request.is_ajax(): 
        idb = request.GET.get("id","")
        get_object_or_404(proyectos,pk=idb).delete()
        historiales(request,["proyecto","eliminar",idb])
        return render(request,'proyecto/proyecto/ajax_proyecto.html',{'lista':proyectos,'n':'proyectoU','estado':estado})     

@login_required(login_url='/')
def mostrarproyecto(request):
    proyectos = proyecto.objects.filter(pk = request.GET['id'])
    return render(request,'proyecto/proyecto/mostrarproyecto.html',{'lista':proyectos})

@login_required(login_url='/')
def mostrarsolicitud(request):
    solicitudes = proyecto.objects.filter(pk = request.GET['id'])
    return render(request,'proyecto/proyecto/mostrarsolicitud.html',{'lista':solicitudes})  

@login_required(login_url='/')
def editarsolicitud(request):
    if request.method == 'POST': 
        idp = request.POST['id']
        solicitudes = proyecto.objects.filter(idsolicitud_id = idp)
        a=get_object_or_404(solicitud,pk=idp)
        form=formSolicitud(request.POST, request.FILES, instance=a)
        if form.is_valid():
            form.save()       
            historiales(request,["solicitud","actualizar",idp])
            return render(request,'proyecto/proyecto/mostrarsolicitud.html',{'lista':solicitudes}) 

             
        else:
            return render(request,'proyecto/proyecto/form_soli.html',{'formu':form})             
    else:
        idp = request.GET["id"]
        a=get_object_or_404(solicitud,pk=idp)
        formuS = formSolicitud(instance=a)
        return render(request,'proyecto/proyecto/modalS.html',{'nombre':formuS,'url':'editarsolicitud','n':'solicitudU','u':'solicitudU','i':idp}) 

    


@login_required(login_url='/')
def traerparticipantes(request):
    data= []
    doc = []
    alu = []
    adm = []
    otr = []
    mod = []
    par = []
    for con in docente.objects.filter(estadosistema= True).order_by('-id'):
        doc.append({'idd':con.id,'nombres':con.nombre + ' '+ con.apellido, 'codigo':con.codigo})

    for con in alumno.objects.filter(estadosistema= True).order_by('-id'):
        alu.append({'idd':con.id,'nombres':con.nombre + ' '+ con.apellido, 'codigo':con.codigo})

    for con in administrativo.objects.filter(estadosistema= True).order_by('-id'):
        adm.append({'idd':con.id,'nombres':con.nombre + ' '+ con.apellido, 'codigo':con.codigo})

sisinvestigacion/apps/proyecto/templates/proyecto/proyecto/participantes/form.html
{% csrf_token %}
    <label for="id_nombre" 
    {% if formu.nombre.errors %}
      {% for error in formu.nombre.errors %}
        data-html="true" data-toggle="popover" data-content="
            <p style='color:red; font-size: 13px; margin: 0 0 0px;'> {{ error|escape }}</p>
        "
      {% endfor %}
    {% endif %}
    >Nombres:</label>
    {{formu.nombre.errors}}
    {{formu.nombre}}    

    <label for="id_apellido" 
    {% if formu.apellido.errors %}
      {% for error in formu.apellido.errors %}
        data-html="true" data-toggle="popover" data-content="
            <p style='color:red; font-size: 13px; margin: 0 0 0px;'> {{ error|escape }}</p>
        "
      {% endfor %}
    {% endif %}
    >Apellidos:</label>
    {{formu.apellido.errors}}
    {{formu.apellido}}    

    <label for="id_codigo" 
    {% if formu.codigo.errors %}
      {% for error in formu.codigo.errors %}
        data-html="true" data-toggle="popover" data-content="
            <p style='color:red; font-size: 13px; margin: 0 0 0px;'> {{ error|escape }}</p>
        "
      {% endfor %}
    {% endif %}
    >Código:</label>
    {{formu.codigo.errors}}
    {{formu.codigo}}        

sisinvestigacion/apps/proyecto/templates/proyecto/proyecto/participantes/modal.html
<div id="Modal{{n}}" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                 <h1>{{n}}</h1>
                 <form id="formulario{{n}}">
                    {% csrf_token %}
                    <div class="ibox-content">
                    {{nombre}}
                    </div>
                 </form> 
            </div>
            <div class="modal-footer">
                <button class="btn btn-sm btn-primary guar" onclick="guardarP('{{url}}','{{n}}','{{u}}','{{t}}')" type="button">guardar</button>
                <button type="button"  class="btn btn-sm  btn-danger" onclick="cerrarModal('Modal{{n}}')"> Cancelar</button>
            </div>
        </div>

    </div>
</div>

sisinvestigacion/apps/proyecto/templates/proyecto/proyecto/participantes/mostrarparticipante.html
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
    <br>
        <ol class="breadcrumb">
            <li>
                <a href="/">Home</a>
            </li>
            <li class="active">
                <strong>Mostrar Participantes</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2"></div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title form-inline">
                  <button type="button" onclick="cargar('registro_proyecto')" class="btn btn-white"><i class="fa fa-chevron-left"></i> Atrás </button> <br>             
                  
                </div>
                <div class="ibox-content table-responsive">
                  <table class="table table-hover">
                    <caption>Lista de participantes</caption>
                    <a href="#editar participantes">
                    Editar
                    <i onclick="actualizarparticipante('participante',{{id}})" class="fa fa-pencil-square-o fa-2x"></i>
                    </a>
                    <thead>
                      <tr>
                        <th>Código</th>
                        <th>Nombres</th>
                        <th>Modalidad</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for p in docente  %}
                      <tr>
                        <td>{{p.iddocente__codigo}}</td>
                        <td>{{p.iddocente__nombre}}  {{p.iddocente__apellido}}</td>
                        <td>{{p.modalidaddocente__descripcion}}</td>
                      </tr>
                      {% endfor %}
                      {% for p in alumno  %}
                      <tr>
                        <td>{{p.idalumno__codigo}}</td>
                        <td>{{p.idalumno__nombre}}  {{p.idalumno__apellido}}</td>
                        <td>{{p.modalidadalumno__descripcion}}</td>
                      </tr>
                      {% endfor %}
                      {% for p in administrativo  %}
                      <tr>
                        <td>{{p.idadministrativo__codigo}}</td>
                        <td>{{p.idadministrativo__nombre}}  {{p.idadministrativo__apellido}}</td>
                        <td>{{p.modalidadadministrativo__descripcion}}</td>
                      </tr>
                      {% endfor %} 
                      {% for p in externo  %}
                      <tr>
                        <td>{{p.idpexterno__codigo}}</td>
                        <td>{{p.idpexterno__nombre}}  {{p.idpexterno__apellido}}</td>
                        <td>{{p.modalidadexterno__descripcion}}</td>
                      </tr>
                      {% endfor %}  
                    </tbody>
                  </table>
                    
                </div>
                
            </div>
        </div>
    </div>
</div>
<div id="participante"></div>
<div id="modalAdd"></div>   
<form  method="get" id="formpar" style="display: none">
    {% csrf_token %}
    <div id="contp">
          
    </div>
</form>

            
{% load static from  staticfiles %}
<script src="{%static 'js/base.js' %}"></script>
<script src="{%static 'js/modal.js' %}"></script>
<script src="{%static 'js/proyecto.js' %}"></script>
<script src="{%static 'js/modalidad.js' %}"></script>